
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class FActores extends javax.swing.JFrame {

    String url = "http://joaquinoworld.shop/mysql.php";
    // Usa esta dirección IP que ya comprobamos que llega al servidor
    ConexionHR cnx = new ConexionHR(url);

    public FActores() {
        initComponents();
        redondear(prosita, 8, false);
        redondear(pmul, 8, false);
        cnx.seleccionar("select generoa from actores group by generoa", cbGenero);
        cnx.entablar("select * from actores", tConsultas);
        styleTable(tConsultas,
                new Color(90, 120, 255), // headerBg
                Color.black, // headerFg
                new Color(250, 250, 255), // rowBg
                new Color(235, 240, 255), // rowAltBg
                new Color(50, 50, 70), // rowFg
                new Color(120, 140, 255), // selectionBg
                30, // rowHeight
                new Font("Segoe UI", Font.BOLD, 13), // headerFont
                new Font("Segoe UI", Font.PLAIN, 12) // rowFont
        );

        cnx.seleccionar("select generoa from actores group by generoa", cbSexo);
        cbSexo.addItem("Todos");
        cbSexo.setSelectedIndex(2);
        tConsultas.getTableHeader().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int col = tConsultas.columnAtPoint(evt.getPoint());
                String nombreColumna = tConsultas.getColumnName(col);

                String sql = "SELECT * FROM actores ORDER BY " + nombreColumna;
                cnx.entablar(sql, tConsultas);
            }
        });
        styleButton(bInterpretacion, 10,
                new Color(0, 153, 255), // color inicial
                new Color(0, 102, 255), // color final
                Color.WHITE // color del texto
        );
    }

    public static void redondear(JComponent comp, int radius, boolean conBorde) {

        comp.setOpaque(false); // para permitir las esquinas redondeadas

        comp.setBorder(new Border() {

            @Override
            public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {

                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Fondo redondeado
                g2.setColor(comp.getBackground());
                g2.fillRoundRect(0, 0, comp.getWidth(), comp.getHeight(), radius, radius);

                // Si el usuario quiere borde, lo pintamos
                if (conBorde) {
                    g2.setColor(Color.BLACK); // puedes cambiarlo si quieres
                    g2.drawRoundRect(0, 0, comp.getWidth() - 1, comp.getHeight() - 1, radius, radius);
                }

                g2.dispose();
            }

            @Override
            public Insets getBorderInsets(Component c) {
                // Si no hay borde, ponemos margen mínimo
                return conBorde
                        ? new Insets(radius, radius, radius, radius)
                        : new Insets(2, 2, 2, 2);
            }

            @Override
            public boolean isBorderOpaque() {
                return false;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        prosita = new javax.swing.JPanel();
        bAgregar = new componentes.botonPersonalizado();
        bActualizar = new componentes.botonPersonalizado();
        bBorrar = new componentes.botonPersonalizado();
        bNuevo = new componentes.botonPersonalizado();
        bPDF = new componentes.botonPersonalizado();
        bGrafica = new componentes.botonPersonalizado();
        bInterpretacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tConsultas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tNombre = new componentes.textBoxPersonalizado();
        tNacionalidad = new componentes.textBoxPersonalizado();
        tFechaNac = new componentes.textBoxPersonalizado();
        cbGenero = new javax.swing.JComboBox<>();
        pmul = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbSexo = new javax.swing.JComboBox<>();
        cbDecada = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        bBuscarFiltro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bTodo = new javax.swing.JButton();
        bAgrupar = new javax.swing.JButton();
        tID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 18, -1, 86));

        prosita.setBackground(new java.awt.Color(255, 204, 204));

        bAgregar.setxSombra(false);
        bAgregar.setxTamañoSombra(0);
        bAgregar.setxTexto("Add");
        bAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAgregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bAgregarLayout = new javax.swing.GroupLayout(bAgregar);
        bAgregar.setLayout(bAgregarLayout);
        bAgregarLayout.setHorizontalGroup(
            bAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        bAgregarLayout.setVerticalGroup(
            bAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bActualizar.setxColorNormal(new java.awt.Color(102, 204, 255));
        bActualizar.setxColorTexto(new java.awt.Color(0, 102, 255));
        bActualizar.setxSombra(false);
        bActualizar.setxTamañoSombra(0);
        bActualizar.setxTexto("Update");
        bActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bActualizarLayout = new javax.swing.GroupLayout(bActualizar);
        bActualizar.setLayout(bActualizarLayout);
        bActualizarLayout.setHorizontalGroup(
            bActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        bActualizarLayout.setVerticalGroup(
            bActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bBorrar.setxColorNormal(new java.awt.Color(153, 153, 153));
        bBorrar.setxSombra(false);
        bBorrar.setxTamañoSombra(0);
        bBorrar.setxTexto("Delete");
        bBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBorrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bBorrarLayout = new javax.swing.GroupLayout(bBorrar);
        bBorrar.setLayout(bBorrarLayout);
        bBorrarLayout.setHorizontalGroup(
            bBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );
        bBorrarLayout.setVerticalGroup(
            bBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bNuevo.setxColorNormal(new java.awt.Color(255, 255, 255));
        bNuevo.setxColorTexto(new java.awt.Color(0, 0, 0));
        bNuevo.setxSombra(false);
        bNuevo.setxTamañoSombra(0);
        bNuevo.setxTexto("New");
        bNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bNuevoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bNuevoLayout = new javax.swing.GroupLayout(bNuevo);
        bNuevo.setLayout(bNuevoLayout);
        bNuevoLayout.setHorizontalGroup(
            bNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        bNuevoLayout.setVerticalGroup(
            bNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        bPDF.setxColorNormal(new java.awt.Color(255, 255, 255));
        bPDF.setxColorTexto(new java.awt.Color(0, 0, 0));
        bPDF.setxSombra(false);
        bPDF.setxTamañoSombra(0);
        bPDF.setxTexto("PDF");
        bPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPDFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bPDFLayout = new javax.swing.GroupLayout(bPDF);
        bPDF.setLayout(bPDFLayout);
        bPDFLayout.setHorizontalGroup(
            bPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        bPDFLayout.setVerticalGroup(
            bPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        bGrafica.setxColorNormal(new java.awt.Color(255, 255, 255));
        bGrafica.setxColorTexto(new java.awt.Color(0, 0, 0));
        bGrafica.setxSombra(false);
        bGrafica.setxTamañoSombra(0);
        bGrafica.setxTexto("Grafic");
        bGrafica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bGraficaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bGraficaLayout = new javax.swing.GroupLayout(bGrafica);
        bGrafica.setLayout(bGraficaLayout);
        bGraficaLayout.setHorizontalGroup(
            bGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        bGraficaLayout.setVerticalGroup(
            bGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        bInterpretacion.setText("Interpretaciones");
        bInterpretacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInterpretacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout prositaLayout = new javax.swing.GroupLayout(prosita);
        prosita.setLayout(prositaLayout);
        prositaLayout.setHorizontalGroup(
            prositaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prositaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bInterpretacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        prositaLayout.setVerticalGroup(
            prositaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prositaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(prositaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bInterpretacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bGrafica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(prosita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 980, -1));

        tConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tConsultasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tConsultas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 471, 608, 220));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 267, 104, 43));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, 104, 43));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Genero:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 322, 104, 43));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nacionalidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 372, 104, 43));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fehca nacimiento:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 428, 104, 43));
        jPanel1.add(tNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 266, 194, 43));
        jPanel1.add(tNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 371, 194, 43));
        jPanel1.add(tFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 427, 194, 43));

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masculino", "femenino" }));
        jPanel1.add(cbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 332, 194, -1));

        javax.swing.GroupLayout pmulLayout = new javax.swing.GroupLayout(pmul);
        pmul.setLayout(pmulLayout);
        pmulLayout.setHorizontalGroup(
            pmulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pmulLayout.setVerticalGroup(
            pmulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        jPanel1.add(pmul, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 214, 660, -1));

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDecada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "1980", "1990", "2000", "2010" }));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Filtros");

        bBuscarFiltro.setText("Filter");
        bBuscarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarFiltroActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Genero");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Decada");

        bTodo.setText("Everything");
        bTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTodoActionPerformed(evt);
            }
        });

        bAgrupar.setText("Agrupar por género");
        bAgrupar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgruparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bBuscarFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbDecada, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                            .addComponent(cbSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                    .addComponent(bAgrupar, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bBuscarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAgrupar)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 471, 240, -1));
        jPanel1.add(tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 224, 194, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAgregarMouseClicked
        String id = tID.getText();
        String nombre = tNombre.getText();
        String genero = cbGenero.getSelectedItem().toString();
        String nacionalidad = tNacionalidad.getText();
        String fechaNac = tNacionalidad.getText();
        String valores[] = new String[]{id, nombre, genero, nacionalidad, fechaNac};
        cnx.insertar("actores", valores);
        cnx.entablar("select * from actores", tConsultas);
    }//GEN-LAST:event_bAgregarMouseClicked

    private void bActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bActualizarMouseClicked
        String id = tID.getText();
        String nombre = tNombre.getText();
        String genero = cbGenero.getSelectedItem().toString();
        String nacionalidad = tNacionalidad.getText();
        String fechaNac = tFechaNac.getText();
        String valores[] = new String[]{id, nombre, genero, nacionalidad, fechaNac};
        cnx.actualizar2("actores", valores);
        cnx.entablar("select * from actores", tConsultas);
    }//GEN-LAST:event_bActualizarMouseClicked

    private void bBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBorrarMouseClicked
        String id = tID.getText();
        String nombre = tNombre.getText();
        String genero = cbGenero.getSelectedItem().toString();
        String nacionalidad = tNacionalidad.getText();
        String fechaNac = tFechaNac.getText();
        String valores[] = new String[]{id, nombre, genero, nacionalidad, fechaNac};
        cnx.borrar3("filmacion", valores);
        cnx.borrar3("actores", valores);
        cnx.entablar("select * from actores", tConsultas);
    }//GEN-LAST:event_bBorrarMouseClicked

    private void bNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bNuevoMouseClicked
        tID.setText("");
        tNombre.setText("");
        cbGenero.setSelectedIndex(0);
        tNacionalidad.setText("");
        tFechaNac.setText("");
    }//GEN-LAST:event_bNuevoMouseClicked

    private void tConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tConsultasMousePressed
        DefaultTableModel datos = (DefaultTableModel) tConsultas.getModel();
        int renSel = tConsultas.getSelectedRow();
        if (renSel > -1) {
            String id = datos.getValueAt(renSel, 0).toString();
            String nombre = datos.getValueAt(renSel, 1).toString();
            String genero = datos.getValueAt(renSel, 2).toString();
            String nacionalidad = datos.getValueAt(renSel, 3).toString();
            String fechaNac = datos.getValueAt(renSel, 4).toString();

            tID.setText(id);
            tNombre.setText(nombre);
            cbGenero.setSelectedItem(genero);
            tNacionalidad.setText(nacionalidad);
            tFechaNac.setText(fechaNac);
        }
    }//GEN-LAST:event_tConsultasMousePressed

    private void bPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPDFMouseClicked
        String decada = cbDecada.getSelectedItem().toString();
        int decadaMas9 = 0;
        String nombrePDF = "actoresDe" + decada;
        if (!decada.equals("Todos")) {
            decadaMas9 = Integer.parseInt(decada) + 9;
        }
        String sql = "select * from actores";
        if (decada.equals("Todos")) {
            cnx.crearPDF("Actores de todas las décadas", "", sql, new float[]{1f, 1f, 1f, 1f, 1f}, nombrePDF);
            cnx.visualizarPDF(nombrePDF);
        } else {
            sql+=" where year(fechanac) between '"+decada+"' and '"+decadaMas9+"'";
            cnx.crearPDF("Actores de la decada de " + decada, "", sql, new float[]{1f, 1f, 1f, 1f, 1f}, nombrePDF);
            cnx.visualizarPDF(nombrePDF);
        }

    }//GEN-LAST:event_bPDFMouseClicked

    private void bGraficaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGraficaMouseClicked
        String consulta
                = "select generoa, count(*) from actores group by generoa";

        GraficaBarras g = new GraficaBarras(cnx);
        // conexionHR es tu instancia de ConexionHR

        g.crearGrafica(
                consulta,
                "Actores por género",
                "Género",
                "Cantidad",
                pmul, // tu JPanel existente
                "Actores"
        );
    }//GEN-LAST:event_bGraficaMouseClicked

    private void bBuscarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarFiltroActionPerformed
        String genero = cbSexo.getSelectedItem().toString();
        String decada = cbDecada.getSelectedItem().toString();
        int decadaMas9 = 0;
        if (!decada.equals("Todos")) {
            decadaMas9 = Integer.parseInt(decada) + 9;
        }

        String sql = "SELECT * FROM actores";
        ArrayList<String> condiciones = new ArrayList<>();

        if (!(genero.equals("Todos") && decada.equals("Todos"))) {
            if (!genero.equals("Todos")) {
                condiciones.add("generoa = '" + genero + "'");
            }

            if (!decada.equals("Todos")) {
                condiciones.add("YEAR(fechanac) BETWEEN '" + decada + "' AND '" + decadaMas9 + "'");
            }

            // Unir condiciones
            if (!condiciones.isEmpty()) {
                sql += " WHERE " + String.join(" AND ", condiciones);
            }

            cnx.entablar(sql, tConsultas);
            sql = "SELECT * FROM actores";
        } else {
            cnx.entablar("select * from actores", tConsultas);
        }
    }//GEN-LAST:event_bBuscarFiltroActionPerformed

    private void bTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTodoActionPerformed
        cnx.entablar("select * from actores", tConsultas);
    }//GEN-LAST:event_bTodoActionPerformed

    private void bInterpretacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInterpretacionActionPerformed
        String id = tID.getText();
        System.out.println(id);
        int opcion=1;
        FFilmacion ff = new FFilmacion(id,opcion);
        ff.setVisible(true);

    }//GEN-LAST:event_bInterpretacionActionPerformed

    private void bAgruparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgruparActionPerformed
        String sql="select * from actores group by generoa";
        cnx.entablar(sql, tConsultas);
    }//GEN-LAST:event_bAgruparActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
    }//GEN-LAST:event_formWindowClosing
    public static void styleTable(JTable table,
            Color headerBg,
            Color headerFg,
            Color rowBg,
            Color rowAltBg,
            Color rowFg,
            Color selectionBg,
            int rowHeight,
            Font headerFont,
            Font rowFont) {

        // --- Encabezado ---
        JTableHeader header = table.getTableHeader();
        header.setBackground(headerBg);
        header.setForeground(headerFg);
        header.setFont(headerFont);
        header.setOpaque(true);

        // Quita bordes feos del header
        header.setBorder(BorderFactory.createEmptyBorder());

        // --- Filas ---
        table.setRowHeight(rowHeight);
        table.setFont(rowFont);
        table.setForeground(rowFg);

        // Renderer personalizado para colores de filas
        table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable tbl, Object val,
                    boolean isSelected, boolean hasFocus,
                    int row, int col) {

                Component c = super.getTableCellRendererComponent(tbl, val, isSelected, hasFocus, row, col);

                if (isSelected) {
                    c.setBackground(selectionBg);
                    c.setForeground(Color.WHITE);
                } else {
                    c.setBackground(row % 2 == 0 ? rowBg : rowAltBg);
                    c.setForeground(rowFg);
                }

                setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
                return c;
            }
        });

        // Quitar líneas de celda (opcional)
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);

        // Bordes suaves
        table.setIntercellSpacing(new Dimension(0, 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FActores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FActores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FActores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FActores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FActores().setVisible(true);
            }
        });
    }

    public static void styleButton(JButton btn, int radius, Color color1, Color color2, Color textColor) {

        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setContentAreaFilled(false);
        btn.setOpaque(false);
        btn.setForeground(textColor);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 14));

        // Colores originales (para restaurar)
        final Color base1 = color1;
        final Color base2 = color2;

        // Colores aclarados para hover
        final Color hover1 = color1.brighter();
        final Color hover2 = color2.brighter();

        // Estado hover
        final boolean[] isHover = {false};

        // Listener para hover
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isHover[0] = true;
                btn.repaint();
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isHover[0] = false;
                btn.repaint();
            }
        });

        // Pintado personalizado
        btn.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                int width = c.getWidth();
                int height = c.getHeight();

                // Si está en hover, usa colores más claros
                Color start = isHover[0] ? hover1 : base1;
                Color end = isHover[0] ? hover2 : base2;

                GradientPaint gp = new GradientPaint(0, 0, start, width, height, end);
                g2.setPaint(gp);
                g2.fillRoundRect(0, 0, width, height, radius, radius);

                super.paint(g2, c);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.botonPersonalizado bActualizar;
    private componentes.botonPersonalizado bAgregar;
    private javax.swing.JButton bAgrupar;
    private componentes.botonPersonalizado bBorrar;
    private javax.swing.JButton bBuscarFiltro;
    private componentes.botonPersonalizado bGrafica;
    private javax.swing.JButton bInterpretacion;
    private componentes.botonPersonalizado bNuevo;
    private componentes.botonPersonalizado bPDF;
    private javax.swing.JButton bTodo;
    private javax.swing.JComboBox<String> cbDecada;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pmul;
    private javax.swing.JPanel prosita;
    private javax.swing.JTable tConsultas;
    private componentes.textBoxPersonalizado tFechaNac;
    private javax.swing.JTextField tID;
    private componentes.textBoxPersonalizado tNacionalidad;
    private componentes.textBoxPersonalizado tNombre;
    // End of variables declaration//GEN-END:variables
}
