
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaqu
 */
public class FFilmacion extends javax.swing.JFrame {
    String url = "http://joaquinoworld.shop/mysql.php";
    // Usa esta dirección IP que ya comprobamos que llega al servidor
    ConexionHR cnx = new ConexionHR(url);
    
    /**
     * Creates new form FFilmacion
     */
    public FFilmacion() {
        initComponents();
        cnx.entablar("select * from filmacion", tInterpretacion);
        estilizarPanel(pFondo);
        styleTable(tInterpretacion,
                new Color(90, 120, 255), // headerBg
                Color.black, // headerFg
                new Color(250, 250, 255), // rowBg
                new Color(235, 240, 255), // rowAltBg
                new Color(50, 50, 70), // rowFg
                new Color(120, 140, 255), // selectionBg
                30, // rowHeight
                new Font("Segoe UI", Font.BOLD, 13), // headerFont
                new Font("Segoe UI", Font.PLAIN, 12) // rowFont
        );
        cnx.seleccionar("select concat(idactor,'-',nombrea) from actores", cbActor);
        cnx.seleccionar("select titulo from peliculas", cbPelicula);
    }
    public static void styleTable(JTable table,
            Color headerBg,
            Color headerFg,
            Color rowBg,
            Color rowAltBg,
            Color rowFg,
            Color selectionBg,
            int rowHeight,
            Font headerFont,
            Font rowFont) {

        // --- Encabezado ---
        JTableHeader header = table.getTableHeader();
        header.setBackground(headerBg);
        header.setForeground(headerFg);
        header.setFont(headerFont);
        header.setOpaque(true);

        // Quita bordes feos del header
        header.setBorder(BorderFactory.createEmptyBorder());

        // --- Filas ---
        table.setRowHeight(rowHeight);
        table.setFont(rowFont);
        table.setForeground(rowFg);

        // Renderer personalizado para colores de filas
        table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable tbl, Object val,
                    boolean isSelected, boolean hasFocus,
                    int row, int col) {

                Component c = super.getTableCellRendererComponent(tbl, val, isSelected, hasFocus, row, col);

                if (isSelected) {
                    c.setBackground(selectionBg);
                    c.setForeground(Color.WHITE);
                } else {
                    c.setBackground(row % 2 == 0 ? rowBg : rowAltBg);
                    c.setForeground(rowFg);
                }

                setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
                return c;
            }
        });

        // Quitar líneas de celda (opcional)
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);

        // Bordes suaves
        table.setIntercellSpacing(new Dimension(0, 0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tInterpretacion = new javax.swing.JTable();
        cbActor = new javax.swing.JComboBox<>();
        cbPelicula = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bAsignar = new javax.swing.JButton();
        txtPago = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tInterpretacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tInterpretacion);

        cbActor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbPelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Film");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pago");

        bAsignar.setText("to Hire");
        bAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsignarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Actor");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Filmación");

        javax.swing.GroupLayout pFondoLayout = new javax.swing.GroupLayout(pFondo);
        pFondo.setLayout(pFondoLayout);
        pFondoLayout.setHorizontalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pFondoLayout.createSequentialGroup()
                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pFondoLayout.createSequentialGroup()
                                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbActor, 0, 169, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbPelicula, 0, 155, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))))
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pFondoLayout.setVerticalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbPelicula, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAsignar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(cbActor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAsignarActionPerformed
        String id=cnx.consultar("select nombre").toString();
        
    }//GEN-LAST:event_bAsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FFilmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FFilmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FFilmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FFilmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FFilmacion().setVisible(true);
            }
        });
    }
    public static void estilizarPanel(JPanel parent) {

    Color rojoBase = new Color(220, 53, 69);     // estilo bootstrap danger
    Color rojoClaro = new Color(245, 108, 118);
    Color rojoOscuro = new Color(173, 30, 45);
    Color texto = Color.WHITE;

    for (Component c : parent.getComponents()) {

        // ----- BOTONES -----
        if (c instanceof JButton btn) {
            btn.setBackground(rojoBase);
            btn.setForeground(texto);
            btn.setFocusPainted(false);
            btn.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));
            btn.setCursor(new Cursor(Cursor.HAND_CURSOR));

            btn.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
                @Override
                protected void paintButtonPressed(Graphics g, AbstractButton b) {
                    g.setColor(rojoOscuro);
                    g.fillRoundRect(0, 0, b.getWidth(), b.getHeight(), 18, 18);
                }
            });

            btn.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btn.setBackground(rojoClaro);
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btn.setBackground(rojoBase);
                }
            });
        }

        // ----- JTABLE -----
        if (c instanceof JTable tabla) {
            tabla.setRowHeight(30);
            tabla.setShowGrid(false);
            tabla.setIntercellSpacing(new Dimension(0, 0));
            tabla.setSelectionBackground(rojoClaro);
            tabla.setSelectionForeground(Color.WHITE);
            tabla.setFont(new Font("Segoe UI", Font.PLAIN, 14));

            JTableHeader th = tabla.getTableHeader();
            th.setBackground(rojoBase);
            th.setForeground(texto);
            th.setFont(new Font("Segoe UI", Font.BOLD, 14));
        }

        // ----- JCOMBOBOX -----
        if (c instanceof JComboBox combo) {
            combo.setBackground(rojoBase);
            combo.setForeground(texto);
            combo.setBorder(BorderFactory.createLineBorder(rojoOscuro, 2));
            combo.setFocusable(false);
            combo.setCursor(new Cursor(Cursor.HAND_CURSOR));

            combo.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    combo.setBackground(rojoClaro);
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    combo.setBackground(rojoBase);
                }
            });
        }

        // ----- LABELS -----
        if (c instanceof JLabel lbl) {
            lbl.setForeground(rojoOscuro);
            lbl.setFont(new Font("Segoe UI", Font.BOLD, 14));
        }

        // ----- TEXTFIELDS -----
        if (c instanceof JTextField txt) {
            txt.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(rojoOscuro, 2),
                    BorderFactory.createEmptyBorder(5, 10, 5, 10)
            ));
            txt.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        }

        // Si hay paneles dentro, los estiliza recursivamente
        if (c instanceof JPanel panelHijo) {
            estilizarPanel(panelHijo);
        }
    }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAsignar;
    private javax.swing.JComboBox<String> cbActor;
    private javax.swing.JComboBox<String> cbPelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pFondo;
    private javax.swing.JTable tInterpretacion;
    private javax.swing.JTextField txtPago;
    // End of variables declaration//GEN-END:variables
}
